# Generated by Django 5.1.2 on 2024-12-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subcategory_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='categories/cover/'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
