# Generated by Django 5.1.2 on 2024-11-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Bags', 'Bags'), ('Jewellery', 'Jewellery')], default='Jewellery', max_length=50),
        ),
    ]
